name: Genres
modelClass: DigArt\Ecole\Models\Genre
form: $/digart/ecole/models/genre/fields.yaml
defaultRedirect: digart/ecole/genres
create:
    redirect: 'digart/ecole/genres/update/:id'
    redirectClose: digart/ecole/genres
update:
    redirect: digart/ecole/genres
    redirectClose: digart/ecole/genres
