list: $/digart/ecole/models/interlocuteur/columns.yaml
modelClass: DigArt\Ecole\Models\Interlocuteur
title: Interlocuteurs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'digart/ecole/interlocuteurs/update/:id'
filter: config_filter.yaml