scopes:
    is_actif:
        label: Actif
        type: switch
        default: 2
        conditions:
            - is_actif <> true
            - is_actif = true
    fonctions:
        label: Fonctions
        modelClass: DigArt\Ecole\Models\Fonction
        conditions: id in (select interloc_id from digart_ecole_inter_fct where fct_id in (:filtered))
        nameFrom: designation