name: Interlocuteurs
form: $/digart/ecole/models/interlocuteur/fields.yaml
modelClass: DigArt\Ecole\Models\Interlocuteur
defaultRedirect: digart/ecole/interlocuteurs
create:
    redirect: 'digart/ecole/interlocuteurs/update/:id'
    redirectClose: digart/ecole/interlocuteurs
update:
    redirect: digart/ecole/interlocuteurs
    redirectClose: digart/ecole/interlocuteurs
