suivis:
    readOnly: true
    label: Suivi
    emptyMessage: Aucun suivi pour le moment
    view:
        list: $/digart/ecole/models/suiviactivite/interlocuteur_columns.yaml
        showSearch: true
        scope: Ouverts