title: Suivis
modelClass: DigArt\Ecole\Models\Suivi
list: $/digart/ecole/models/suivi/columns.yaml
recordUrl: 'digart/ecole/suivis/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: debut
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml