name: Suivis
form: $/digart/ecole/models/suivi/fields.yaml
modelClass: DigArt\Ecole\Models\Suivi
defaultRedirect: digart/ecole/suivis
create:
    redirect: 'digart/ecole/suivis/update/:id'
    redirectClose: digart/ecole/suivis
update:
    redirect: digart/ecole/suivis
    redirectClose: digart/ecole/suivis
