scopes:
    #ecole:
        #label: Eleves
        #modelClass: DigArt\Ecole\Models\Eleve
        #conditions: eleve_id in (:filtered)
        #nameFrom: FullName     
    # show_actifs:
    #     label: En cours
    #     type: checkbox
    #     modelClass: DigArt\Ecole\Models\Suivi
    #     scope: Ouverts
    #     default: 1     
    show_actif:
        label: En cours
        type: switch
        modelClass: DigArt\Ecole\Models\Statut
        default: 2
        conditions:
            - statut_id in (select id from digart_ecole_statuts where is_finished = 1)
            - statut_id in (select id from digart_ecole_statuts where is_finished <> 1)          
    eleve:
        label: Eleves
        type: group
        modelClass: DigArt\Ecole\Models\Eleve
        conditions: eleve_id in (:filtered)
        options: getPrenomNomElevesOptions   
    ecole:
        label: Ecole
        modelClass: DigArt\Ecole\Models\Ecole
        conditions: eleve_id in (select id from digart_ecole_eleves where ecole_id in (:filtered))
        nameFrom: designation    
    pathologies:
        label: Pathologies
        modelClass: DigArt\Ecole\Models\Pathologie
        conditions: id in (select suivi_id from digart_ecole_path_suivi where path_id in (:filtered))
        nameFrom: designation   
    therapies:
        label: Thérapies
        modelClass: DigArt\Ecole\Models\Therapie
        conditions: id in (select suivi_id from digart_ecole_suivis_activ where therapie_id in (:filtered))
        nameFrom: designation        
    evolutions:
        label: Evolutions
        modelClass: DigArt\Ecole\Models\Evolution
        conditions: id in (select suivi_id from digart_ecole_suivis_activ where evolution_id in (:filtered))
        nameFrom: designation  
    therapeutes:
        label: Thérapeutes
        modelClass: DigArt\Ecole\Models\Interlocuteur
        conditions: id in (select suivi_id from digart_ecole_suivis_activ where interlocuteur_id in (:filtered))
        #nameFrom: FullName     
        options: getPrenomNomInterlocuteursOptions
    statut:
        label: Statuts
        modelClass: DigArt\Ecole\Models\Statut
        conditions: statut_id in (:filtered)
        nameFrom: designation                        
    periode_debut:
        label: Début
        type: daterange
        conditions: debut >= ':after' AND debut <= ':before'
    periode_fin:
        label: Fin
        type: daterange
        conditions: fin >= ':after' AND fin <= ':before'