name: 'Types de faits'
modelClass: DigitalArtisan\Enseignement\Models\TypeFait
form: $/digitalartisan/enseignement/models/typefait/fields.yaml
defaultRedirect: digitalartisan/enseignement/typesfaits
create:
    redirect: 'digitalartisan/enseignement/typesfaits/update/:id'
    redirectClose: digitalartisan/enseignement/typesfaits
update:
    redirect: digitalartisan/enseignement/typesfaits
    redirectClose: digitalartisan/enseignement/typesfaits
preview: {  }
