name: 'Types de faits'
modelClass: DigArt\Ecole\Models\TypeFait
form: $/digart/ecole/models/typefait/fields.yaml
defaultRedirect: digart/ecole/typesfaits
create:
    redirect: 'digart/ecole/typesfaits/update/:id'
    redirectClose: digart/ecole/typesfaits
update:
    redirect: digart/ecole/typesfaits
    redirectClose: digart/ecole/typesfaits
preview: {  }
