plugin:
    name: 'Enseignement spécialisé'
    description: 'Gère le suivi de l''enseignement spécialisé'
    author: digital-artisan
    icon: oc-icon-trophy
    homepage: www.digital-artisan.ch
permissions:
    digart.ecole.suivis:
        tab: 'ESP - Protocoles'
        label: 'Gère le suivi des élèves'
        order: '50'
    digart.ecole.pathologies:
        tab: 'ESP - Protocoles'
        label: 'Gère les pathologies'
    digart.ecole.therapies:
        tab: 'ESP - Protocoles'
        label: 'Gère les mesures (thérapies) à disposition'
    digart.ecole.statuts:
        tab: 'ESP - Protocoles'
        label: 'Gère les statuts de la prise en charge'
    digart.ecole.types:
        tab: 'ESP - Protocoles'
        label: 'Gère les types d''activités liées aux suivis'
    digart.ecole.evolutions:
        tab: 'ESP - Protocoles'
        label: 'Gère les types d ''évolution des mesures'
    digart.ecole.statistiques:
        tab: 'ESP - Protocoles'
        label: 'Accède aux statistiques'
    digart.ecole.eleves:
        tab: 'ESP - Ressources humaines'
        label: 'Gère les élèves de l''enseignement spécialisé'
        order: '51'
    digart.ecole.interlocuteurs:
        tab: 'ESP - Ressources humaines'
        label: 'Gère les interlocuteurs'
    digart.ecole.enseignants:
        tab: 'ESP - Ressources humaines'
        label: 'Gère les enseignants'
    digart.ecole.fonctions:
        tab: 'ESP - Ressources humaines'
        label: 'Gère les fonctions professionnelles des interlocuteurs'
    digart.ecole.prochesroles:
        tab: 'ESP - Ressources humaines'
        label: 'Gère les rôles des proches (parents et autres)'
    digart.ecole.ecoles:
        tab: 'ESP - Structures'
        label: 'Gère les écoles'
        order: '52'
    digart.ecole.cercles:
        tab: 'ESP - Structures'
        label: 'Gère les cercles des écoles'
    digart.ecole.annees:
        tab: 'ESP - Structures'
        label: 'Gère les années scolaires'
    digart.ecole.programmes:
        tab: 'ESP - Structures'
        label: 'Gère les programmes et les cycles liés'
    digart.ecole.cycles:
        tab: 'ESP - Structures'
        label: 'Gère les cycles'
    digart.ecole.volees:
        tab: 'ESP - Structures'
        label: 'Gère les volées'
    digart.ecole.ecoletype:
        tab: 'ESP - Structures'
        label: 'Gère les types d''écoles'
    digart.ecole.pays:
        tab: 'ESP - Bases'
        label: 'Gère les pays'
        order: '53'
    digart.ecole.langues:
        tab: 'ESP - Bases'
        label: 'Gère les langues des différents protagonistes'
    digart.ecole.prochespermis:
        tab: 'ESP - Bases'
        label: 'Gère les types de permis des élèves et des proches'
    digart.ecole.genres:
        tab: 'ESP - Bases'
        label: 'Gère les genres des différents protagonistes'
    digart.ecole.passages:
        tab: 'ESP - Bases'
        label: 'Gère les types de passages d''une année à l''autre pour les élèves'
    digart.ecole.typesfaits:
        tab: 'ESP - Bases'
        label: 'Gère les types de faits des enseignants'
    digart.ecole.can_restore:
        tab: 'ESP - Droits spécifiques'
        label: 'Peut restaurer des enregistrement effacés (softdeletes)'
        order: '53'
    digart.ecole.can_bouclement:
        tab: 'ESP - Droits spécifiques'
        label: 'Peut boucler une année spécifique (créée une nouvelle année dans l''historique des élèves)'
navigation:
    protocoles:
        label: Protocoles
        url: digart/ecole/suivis
        icon: icon-pencil
        permissions:
            - digart.ecole.suivis
            - digart.ecole.therapies
            - digart.ecole.statuts
            - digart.ecole.types
            - digart.ecole.pathologies
            - digart.ecole.evolutions
            - digart.ecole.statistiques
        sideMenu:
            suivi:
                label: 'Suivi des élèves'
                url: digart/ecole/suivis
                icon: icon-stethoscope
                permissions:
                    - digart.ecole.suivis
            activites:
                label: Activités
                url: digart/ecole/suivisactivites
                icon: icon-calendar-o
                permissions:
                    - digart.ecole.suivis
            pathologies:
                label: Pathologies
                url: digart/ecole/pathologies
                icon: icon-bug
                permissions:
                    - digart.ecole.pathologies
            mesures:
                label: Mesures
                url: digart/ecole/therapies
                icon: icon-wheelchair
                permissions:
                    - digart.ecole.therapies
            statuts:
                label: 'Statuts des suivis'
                url: digart/ecole/statuts
                icon: icon-tags
                permissions:
                    - digart.ecole.statuts
            type-activites:
                label: 'Types d''activités'
                url: digart/ecole/types
                icon: icon-suitcase
                permissions:
                    - digart.ecole.types
            evolutions:
                label: 'Évolutions des mesures'
                url: digart/ecole/evolutions
                icon: icon-signal
                permissions:
                    - digart.ecole.evolutions
            statistiques:
                label: Statistiques
                url: digart/ecole/statistiques
                icon: icon-calculator
                permissions:
                    - digart.ecole.statistiques
    ressources-humaines:
        label: 'Ressources humaines'
        url: digart/ecole/eleves
        icon: icon-child
        permissions:
            - digart.ecole.eleves
            - digart.ecole.interlocuteurs
            - digart.ecole.enseignants
            - digart.ecole.fonctions
            - digart.ecole.prochesroles
        sideMenu:
            eleves:
                label: Elèves
                url: digart/ecole/eleves
                icon: icon-mortar-board
                permissions:
                    - digart.ecole.eleves
            interlocuteurs:
                label: 'Interlocuteurs externes'
                url: digart/ecole/interlocuteurs
                icon: icon-users
                permissions:
                    - digart.ecole.interlocuteurs
            enseignants:
                label: Enseignants
                url: digart/ecole/enseignants
                icon: icon-coffee
                permissions:
                    - digart.ecole.enseignants
            fonctions:
                label: 'Fonctions professionnelles'
                url: digart/ecole/fonctions
                icon: icon-ambulance
                permissions:
                    - digart.ecole.fonctions
                attributes: {  }
            roles-proches:
                label: 'Rôles des proches'
                url: digart/ecole/prochesroles
                icon: icon-link
                permissions:
                    - digart.ecole.prochesroles
    structures:
        label: Structures
        url: digart/ecole/ecoles
        icon: icon-sitemap
        permissions:
            - digart.ecole.ecoles
            - digart.ecole.cercles
            - digart.ecole.annees
            - digart.ecole.programmes
            - digart.ecole.cycles
            - digart.ecole.volees
            - digart.ecole.ecoletype
            - digart.ecole.passages
        sideMenu:
            ecoles:
                label: Ecoles
                url: digart/ecole/ecoles
                icon: icon-institution
                permissions:
                    - digart.ecole.ecoles
            cercles:
                label: 'Cercles scolaires'
                url: digart/ecole/cercles
                icon: icon-circle-o
                permissions:
                    - digart.ecole.cercles
            annees:
                label: 'Années scolaires'
                url: digart/ecole/annees
                icon: icon-calendar
                permissions:
                    - digart.ecole.annees
            programmes:
                label: Programmes
                url: digart/ecole/programmes
                icon: icon-sort-alpha-asc
                permissions:
                    - digart.ecole.programmes
            cycles:
                label: Cycles
                url: digart/ecole/cycles
                icon: icon-bars
                permissions:
                    - digart.ecole.cycles
            volees:
                label: Volées
                url: digart/ecole/volees
                icon: icon-sitemap
                permissions:
                    - digart.ecole.volees
            ecoles-types:
                label: 'Types d''écoles'
                url: digart/ecole/ecolestypes
                icon: icon-list-ul
                permissions:
                    - digart.ecole.ecoletype
            passages:
                label: Passages
                url: digart/ecole/passages
                icon: icon-thumbs-o-up
                permissions:
                    - digart.ecole.passages
    bases:
        label: Bases
        url: digart/ecole/pays
        icon: icon-list
        permissions:
            - digart.ecole.pays
            - digart.ecole.genres
            - digart.ecole.langues
            - digart.ecole.prochespermis
            - digart.ecole.typesfaits
        sideMenu:
            pays:
                label: Pays
                url: digart/ecole/pays
                icon: icon-flag
                permissions:
                    - digart.ecole.pays
            langues:
                label: Langues
                url: digart/ecole/langues
                icon: icon-comments
                permissions:
                    - digart.ecole.langues
            permis:
                label: 'Types de permis'
                url: digart/ecole/prochespermis
                icon: icon-suitcase
                permissions:
                    - digart.ecole.prochespermis
            Genres:
                label: Genres
                url: digart/ecole/genres
                icon: icon-transgender
                permissions:
                    - digart.ecole.genres
            types-faits:
                label: 'Types de faits'
                url: digart/ecole/typesfaits
                icon: icon-phone
                permissions:
                    - digart.ecole.typesfaits
