plugin:
    name: 'digitalartisan.enseignement::lang.plugin.name'
    description: 'Gère le suivi de l''enseignement spécialisé'
    author: digital-artisan
    icon: oc-icon-trophy
    homepage: ''
permissions:
    digitalartisan.enseignement.interlocuteurs:
        tab: 'Ressources humaines'
        label: 'Gère les interlocuteurs'
    digitalartisan.enseignement.statuts:
        tab: Protocoles
        label: 'Gère les statuts de la prise en charge'
    digitalartisan.enseignement.eleves:
        tab: 'Ressources humaines'
        label: 'Gère les élèves de l''enseignement spécialisé'
    digitalartisan.enseignement.volees:
        tab: Structures
        label: 'Gère les volées'
    digitalartisan.enseignement.annees:
        tab: Structures
        label: 'Gère les années scolaires'
    digitalartisan.enseignement.ecoles:
        tab: Structures
        label: 'Gère les écoles'
    digitalartisan.enseignement.pathologies:
        tab: Protocoles
        label: 'Gère les pathologies des cas'
    digitalartisan.enseignement.fonctions:
        tab: Protocoles
        label: 'Gère les fonctions des suivis'
    digitalartisan.enseignement.suivis:
        tab: Protocoles
        label: 'Gère le suivi des élèves'
    digitalartisan.enseignement.therapies:
        tab: Protocoles
        label: 'Gère les thérapies à disposition'
    digitalartisan.enseignement.types:
        tab: Protocoles
        label: 'Gère les types d''activités liées aux suivis'
    digitalartisan.enseignement.prochesroles:
        tab: 'Ressources humaines'
        label: 'Gère les rôles des proches (parents et autres)'
    digitalartisan.enseignement.enseignants:
        tab: 'Ressources humaines'
        label: 'Gère les enseignants'
    digitalartisan.enseignement.pays:
        tab: Structures
        label: 'Gère les pays'
    digitalartisan.enseignement.cercles:
        tab: Structures
        label: 'Gère les cercles des écoles'
    digitalartisan.enseignement.genres:
        tab: Structures
        label: 'Gère les genres des différents protagonistes'
    digitalartisan.enseignement.langues:
        tab: Structures
        label: 'Gère les langues des différents protagonistes'
    digitalartisan.enseignement.prochespermis:
        tab: 'Ressources humaines'
        label: 'Gère les types de permis des proches'
    digitalartisan.enseignement.passages:
        tab: Structures
        label: 'Gère les types de passages d''une année à l''autre pour les élèves'
    digitalartisan.enseignement.typesfaits:
        tab: Structures
        label: 'Gère les types de faits des enseignants'
    digitalartisan.enseignement.cycles:
        tab: Structures
        label: 'Gère les cycles'
    digitalartisan.enseignement.programmes:
        tab: Structures
        label: 'Gère les programmes et les cycles liés'
navigation:
    protocoles:
        label: Protocoles
        url: digitalartisan/enseignement/suivis
        icon: icon-pencil
        sideMenu:
            suivi:
                label: 'Suivi des élèves'
                url: digitalartisan/enseignement/suivis
                icon: icon-stethoscope
            activites:
                label: Activités
                url: digitalartisan/enseignement/suivisactivites
                icon: icon-calendar-o
            mesures:
                label: Mesures
                url: digitalartisan/enseignement/therapies
                icon: icon-wheelchair
            statuts:
                label: 'Statuts des suivis'
                url: digitalartisan/enseignement/statuts
                icon: icon-tags
            type-activites:
                label: 'Types d''activités'
                url: digitalartisan/enseignement/types
                icon: icon-suitcase
    ressources-humaines:
        label: 'Ressources humaines'
        url: digitalartisan/enseignement/eleves
        icon: icon-child
        sideMenu:
            eleves:
                label: Elèves
                url: digitalartisan/enseignement/eleves
                icon: icon-mortar-board
            interlocuteurs:
                label: 'Interlocuteurs externes'
                url: digitalartisan/enseignement/interlocuteurs
                icon: icon-users
            enseignants:
                label: Enseignants
                url: digitalartisan/enseignement/enseignants
                icon: icon-coffee
            pathologies:
                label: Pathologies
                url: digitalartisan/enseignement/pathologies
                icon: icon-bug
            fonctions:
                label: 'Fonctions professionnelles'
                url: digitalartisan/enseignement/fonctions
                icon: icon-ambulance
                attributes: {  }
            roles-proches:
                label: 'Rôles des proches'
                url: digitalartisan/enseignement/prochesroles
                icon: icon-link
    structures:
        label: Structures
        url: digitalartisan/enseignement/ecoles
        icon: icon-sitemap
        sideMenu:
            ecoles:
                label: Ecoles
                url: digitalartisan/enseignement/ecoles
                icon: icon-institution
            cercles:
                label: 'Cercles scolaires'
                url: digitalartisan/enseignement/cercles
                icon: icon-circle-o
            annees:
                label: 'Années scolaires'
                url: digitalartisan/enseignement/annees
                icon: icon-calendar
            programmes:
                label: Programmes
                url: digitalartisan/enseignement/programmes
                icon: icon-sort-alpha-asc
            cycles:
                label: Cycles
                url: digitalartisan/enseignement/cycles
                icon: icon-bars
            volees:
                label: Volées
                url: digitalartisan/enseignement/volees
                icon: icon-sitemap
    bases:
        label: Bases
        url: digitalartisan/enseignement/pays
        icon: icon-list
        sideMenu:
            pays:
                label: Pays
                url: digitalartisan/enseignement/pays
                icon: icon-flag
            Genres:
                label: Genres
                url: digitalartisan/enseignement/genres
                icon: icon-transgender
            langues:
                label: Langues
                url: digitalartisan/enseignement/langues
                icon: icon-comments
            permis:
                label: 'Types de permis'
                url: digitalartisan/enseignement/prochespermis
                icon: icon-suitcase
            passages:
                label: Passages
                url: digitalartisan/enseignement/passages
                icon: icon-thumbs-o-up
            types-faits:
                label: 'Types de faits'
                url: digitalartisan/enseignement/typesfaits
                icon: icon-phone
