title: ProchesPermis
modelClass: DigitalArtisan\Enseignement\Models\ProchePermis
list: $/digitalartisan/enseignement/models/prochepermis/columns.yaml
recordUrl: 'digitalartisan/enseignement/prochespermis/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
