name: ProchesPermis
form: $/digitalartisan/enseignement/models/prochepermis/fields.yaml
modelClass: DigitalArtisan\Enseignement\Models\ProchePermis
defaultRedirect: digitalartisan/enseignement/prochespermis
create:
    redirect: 'digitalartisan/enseignement/prochespermis/update/:id'
    redirectClose: digitalartisan/enseignement/prochespermis
update:
    redirect: digitalartisan/enseignement/prochespermis
    redirectClose: digitalartisan/enseignement/prochespermis
