name: ProchesPermis
form: $/digart/ecole/models/prochepermis/fields.yaml
modelClass: DigArt\Ecole\Models\ProchePermis
defaultRedirect: digart/ecole/prochespermis
create:
    redirect: 'digart/ecole/prochespermis/update/:id'
    redirectClose: digart/ecole/prochespermis
update:
    redirect: digart/ecole/prochespermis
    redirectClose: digart/ecole/prochespermis
