name: ProchesRoles
form: $/digart/ecole/models/procherole/fields.yaml
modelClass: DigArt\Ecole\Models\ProcheRole
defaultRedirect: digart/ecole/prochesroles
create:
    redirect: 'digart/ecole/prochesroles/update/:id'
    redirectClose: digart/ecole/prochesroles
update:
    redirect: digart/ecole/prochesroles
    redirectClose: digart/ecole/prochesroles
