name: Types
form: $/digitalartisan/enseignement/models/type/fields.yaml
modelClass: DigitalArtisan\Enseignement\Models\Type
defaultRedirect: digitalartisan/enseignement/types
create:
    redirect: 'digitalartisan/enseignement/types/update/:id'
    redirectClose: digitalartisan/enseignement/types
update:
    redirect: digitalartisan/enseignement/types
    redirectClose: digitalartisan/enseignement/types
