name: Types
form: $/digart/ecole/models/type/fields.yaml
modelClass: DigArt\Ecole\Models\Type
defaultRedirect: digart/ecole/types
create:
    redirect: 'digart/ecole/types/update/:id'
    redirectClose: digart/ecole/types
update:
    redirect: digart/ecole/types
    redirectClose: digart/ecole/types
