title: SuivisActivites
modelClass: DigitalArtisan\Enseignement\Models\SuiviActivite
list: $/digitalartisan/enseignement/models/suiviactivite/suivi_columns.yaml
recordUrl: 'digitalartisan/enseignement/suivisactivites/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: false
defaultSort:
    column: date
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
