title: 'Suivi des activités'
modelClass: DigArt\Ecole\Models\SuiviActivite
list: $/digart/ecole/models/suiviactivite/suivi_columns.yaml
recordUrl: 'digart/ecole/suivisactivites/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: false
defaultSort:
    column: date
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
