name: SuivisActivites
modelClass: DigArt\Ecole\Models\SuiviActivite
form: $/digart/ecole/models/suiviactivite/fields.yaml
defaultRedirect: digart/ecole/suivisactivites
create:
    title: 'Créer une activité de suivi'
    redirect: 'digart/ecole/suivisactivites/update/:id'
    redirectClose: digart/ecole/suivisactivites
update:
    title: 'Mise à jour d''une activité de suivi'
    redirect: digart/ecole/suivisactivites
    redirectClose: digart/ecole/suivisactivites
preview: {  }
