scopes:
    show_actif:
        label: En cours
        type: switch
        modelClass: DigArt\Ecole\Models\ActiviteStatut
        default: 2
        conditions:
            - statut_id in (select id FROM digart_ecole_activites_statuts where is_finished = 1)
            - statut_id in (select id FROM digart_ecole_activites_statuts where is_finished <> 1) 
    suivi:
        label: Suivi
        modelClass: DigArt\Ecole\Models\Suivi
        conditions: suivi_id in (:filtered)
        #nameFrom: id
        options: getIdElevesOptions    
    statuts_suivi:
        label: Statut du suivi
        modelClass: DigArt\Ecole\Models\Statut
        conditions: suivi_id in (SELECT suivi_id FROM digart_ecole_suivi_activites JOIN digart_ecole_suivi ON digart_ecole_suivi.id = digart_ecole_suivi_activites.suivi_id where digart_ecole_suivi.statut_id in (:filtered))
        nameFrom: designation          
    Eleves:
        label: Eleves
        modelClass: DigArt\Ecole\Models\Eleve
        conditions: suivi_id in (SELECT suivi_id FROM digart_ecole_suivi_activites JOIN digart_ecole_suivi ON digart_ecole_suivi.id = digart_ecole_suivi_activites.suivi_id where eleve_id in (:filtered))
        options: getPrenomNomElevesOptions      
    types_activites:
        label: Type d'activité
        modelClass: DigArt\Ecole\Models\Type
        conditions: type_id in (:filtered)
        nameFrom: designation        
    therapies:
        label: Thérapies
        modelClass: DigArt\Ecole\Models\Therapie
        conditions: therapie_id in (:filtered)
        nameFrom: designation                
    interlocteurs:
        label: Interlocuteurs
        modelClass: DigArt\Ecole\Models\Interlocuteur
        conditions: interlocuteur_id in (:filtered)
        options: getPrenomNomInterlocuteursOptions                        
    statuts_activites:
        label: Statut de l'activité
        modelClass: DigArt\Ecole\Models\ActiviteStatut
        conditions: statut_id in (:filtered)
        nameFrom: designation
    periode:
        label: Période
        type: daterange
        conditions: date >= ':after' AND date <= ':before'        