name: Cycles
form: $/digart/ecole/models/cycle/fields.yaml
modelClass: DigArt\Ecole\Models\Cycle
defaultRedirect: digart/ecole/cycles
create:
    redirect: 'digart/ecole/cycles/update/:id'
    redirectClose: digart/ecole/cycles
update:
    redirect: digart/ecole/cycles
    redirectClose: digart/ecole/cycles
