name: Sexes
modelClass: DigitalArtisan\Enseignement\Models\Sexe
form: $/digitalartisan/enseignement/models/sexe/fields.yaml
defaultRedirect: digitalartisan/enseignement/sexes
create:
    redirect: 'digitalartisan/enseignement/sexes/update/:id'
    redirectClose: digitalartisan/enseignement/sexes
update:
    redirect: digitalartisan/enseignement/sexes
    redirectClose: digitalartisan/enseignement/sexes
preview: {  }
