name: Pathologies
form: $/digitalartisan/enseignement/models/pathologie/fields.yaml
modelClass: DigitalArtisan\Enseignement\Models\Pathologie
defaultRedirect: digitalartisan/enseignement/pathologies
create:
    redirect: 'digitalartisan/enseignement/pathologies/update/:id'
    redirectClose: digitalartisan/enseignement/pathologies
update:
    redirect: digitalartisan/enseignement/pathologies
    redirectClose: digitalartisan/enseignement/pathologies
