name: Pathologies
form: $/digart/ecole/models/pathologie/fields.yaml
modelClass: DigArt\Ecole\Models\Pathologie
defaultRedirect: digart/ecole/pathologies
create:
    redirect: 'digart/ecole/pathologies/update/:id'
    redirectClose: digart/ecole/pathologies
update:
    redirect: digart/ecole/pathologies
    redirectClose: digart/ecole/pathologies
