list: $/digart/ecole/models/pathologie/columns.yaml
modelClass: DigArt\Ecole\Models\Pathologie
title: Pathologies
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'digart/ecole/pathologies/update/:id'
filter: config_filter.yaml