name: Annees
form: $/digitalartisan/enseignement/models/annee/fields.yaml
modelClass: DigitalArtisan\Enseignement\Models\Annee
defaultRedirect: digitalartisan/enseignement/annees
create:
    redirect: 'digitalartisan/enseignement/annees/update/:id'
    redirectClose: digitalartisan/enseignement/annees
update:
    redirect: digitalartisan/enseignement/annees
    redirectClose: digitalartisan/enseignement/annees
