name: Années
modelClass: DigArt\Ecole\Models\Annee
form: $/digart/ecole/models/annee/fields.yaml
defaultRedirect: digart/ecole/annees
create:
    title: 'Créer une nouvelle année'
    redirect: 'digart/ecole/annees/update/:id'
    redirectClose: digart/ecole/annees
update:
    title: 'Editer une année'
    redirect: digart/ecole/annees
    redirectClose: digart/ecole/annees
preview: {  }
