name: Pays
form: $/digart/ecole/models/pays/fields.yaml
modelClass: DigArt\Ecole\Models\Pays
defaultRedirect: digart/ecole/pays
create:
    redirect: 'digart/ecole/pays/update/:id'
    redirectClose: digart/ecole/pays
update:
    redirect: digart/ecole/pays
    redirectClose: digart/ecole/pays
