title: Pays
modelClass: DigitalArtisan\Enseignement\Models\Pays
list: $/digitalartisan/enseignement/models/pays/columns.yaml
recordUrl: 'digitalartisan/enseignement/pays/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: designation
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
