name: EcolesTypes
form: $/digart/ecole/models/ecoletype/fields.yaml
modelClass: DigArt\Ecole\Models\EcoleType
defaultRedirect: digart/ecole/ecolestypes
create:
    redirect: 'digart/ecole/ecolestypes/update/:id'
    redirectClose: digart/ecole/ecolestypes
update:
    redirect: digart/ecole/ecolestypes
    redirectClose: digart/ecole/ecolestypes
