title: 'Types d''écoles'
modelClass: DigitalArtisan\Enseignement\Models\EcoleType
list: $/digitalartisan/enseignement/models/ecoletype/columns.yaml
recordUrl: 'digitalartisan/enseignement/ecolestypes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
