name: Passages
form: $/digart/ecole/models/passage/fields.yaml
modelClass: DigArt\Ecole\Models\Passage
defaultRedirect: digart/ecole/passages
create:
    redirect: 'digart/ecole/passages/update/:id'
    redirectClose: digart/ecole/passages
update:
    redirect: digart/ecole/passages
    redirectClose: digart/ecole/passages
