scopes:
    ecole:
        label: Ecole
        modelClass: DigitalArtisan\Enseignement\Models\Ecole
        conditions: ecole_id in (:filtered)
        nameFrom: designation
    pathologies:
        label: Pathologies
        modelClass: DigitalArtisan\Enseignement\Models\Pathologie
        conditions: id in (select eleve_id from digart_ecole_path_eleve where path_id in (:filtered))
        nameFrom: designation                                                                
    genre:
        label: Genres
        modelClass: DigitalArtisan\Enseignement\Models\Genre
        conditions: genre_id in (:filtered)
        nameFrom: designation        
    langue:
        label: Langues maternelles
        modelClass: DigitalArtisan\Enseignement\Models\Langue
        conditions: langue_id in (:filtered)
        nameFrom: designation
    proches:
        label: Proches
        modelClass: DigitalArtisan\Enseignement\Models\Proche
        conditions: id in (select eleve_id from digart_ecole_proches where id in (:filtered))
        #nameFrom: FullName
        options: getPrenomNomProchesOptions           
    is_actif:
        label: Actif
        type: switch
        default: 2
        conditions:
            - is_actif <> true
            - is_actif = true
    show_deleted:
        label: Afficher les supprimés
        type: checkbox
        modelClass: DigitalArtisan\Enseignement\Models\Eleve
        scope: withTrashed
        default: 0            