title: Elèves
modelClass: DigArt\Ecole\Models\Eleve
list: $/digart/ecole/models/eleve/columns.yaml
recordUrl: 'digart/ecole/eleves/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: nom
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
