name: Eleves
modelClass: DigArt\Ecole\Models\Eleve
form: $/digart/ecole/models/eleve/fields.yaml
defaultRedirect: digart/ecole/eleves
create:
    redirect: 'digart/ecole/eleves/update/:id'
    redirectClose: digart/ecole/eleves
update:
    redirect: digart/ecole/eleves
    redirectClose: digart/ecole/eleves
preview: {  }
