name: Therapies
modelClass: DigArt\Ecole\Models\Therapie
form: $/digart/ecole/models/therapie/fields.yaml
defaultRedirect: digart/ecole/therapies
create:
    redirect: 'digart/ecole/therapies/update/:id'
    redirectClose: digart/ecole/therapies
update:
    redirect: digart/ecole/therapies
    redirectClose: digart/ecole/therapies
preview: {  }
