name: Status
modelClass: DigitalArtisan\Enseignement\Models\Status
form: $/digitalartisan/enseignement/models/status/fields.yaml
defaultRedirect: digitalartisan/enseignement/status
create:
    redirect: 'digitalartisan/enseignement/status/update/:id'
    redirectClose: digitalartisan/enseignement/status
update:
    redirect: digitalartisan/enseignement/status
    redirectClose: digitalartisan/enseignement/status
