name: Langues
form: $/digart/ecole/models/langue/fields.yaml
modelClass: DigArt\Ecole\Models\Langue
defaultRedirect: digart/ecole/langues
create:
    redirect: 'digart/ecole/langues/update/:id'
    redirectClose: digart/ecole/langues
update:
    redirect: digart/ecole/langues
    redirectClose: digart/ecole/langues
