name: Fonctions
modelClass: DigArt\Ecole\Models\Fonction
form: $/digart/ecole/models/fonction/fields.yaml
defaultRedirect: digart/ecole/fonctions
create:
    redirect: 'digart/ecole/fonctions/update/:id'
    redirectClose: digart/ecole/fonctions
update:
    redirect: digart/ecole/fonctions
    redirectClose: digart/ecole/fonctions
preview: {  }
