name: Fonctions
modelClass: DigitalArtisan\Enseignement\Models\Fonction
form: $/digitalartisan/enseignement/models/fonction/fields.yaml
defaultRedirect: digitalartisan/enseignement/fonctions
create:
    redirect: 'digitalartisan/enseignement/fonctions/update/:id'
    redirectClose: digitalartisan/enseignement/fonctions
update:
    redirect: digitalartisan/enseignement/fonctions
    redirectClose: digitalartisan/enseignement/fonctions
preview: {  }
