name: Statuts
modelClass: DigArt\Ecole\Models\Statut
form: $/digart/ecole/models/statut/fields.yaml
defaultRedirect: digart/ecole/statuts
create:
    redirect: 'digart/ecole/statuts/update/:id'
    redirectClose: digart/ecole/statuts
update:
    redirect: digart/ecole/statuts
    redirectClose: digart/ecole/statuts
