title: 'Statuts des suivis'
modelClass: DigitalArtisan\Enseignement\Models\Statut
list: $/digitalartisan/enseignement/models/statut/columns.yaml
recordUrl: 'digitalartisan/enseignement/statuts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml