title: Enseignants
modelClass: DigitalArtisan\Enseignement\Models\Enseignant
list: $/digitalartisan/enseignement/models/enseignant/columns.yaml
recordUrl: 'digitalartisan/enseignement/enseignants/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: nom
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml