scopes:
    ecole:
        label: Ecole
        modelClass: DigitalArtisan\Enseignement\Models\Ecole
        conditions: id in (select ens_id from digitalartisan_enseignement_ens_eco where eco_id in (:filtered))
        nameFrom: designation  