scopes:
    ecole:
        label: Ecole
        modelClass: DigitalArtisan\Enseignement\Models\Ecole
        conditions: id in (select ens_id from digitalartisan_enseignement_ens_eco where eco_id in (:filtered))
        nameFrom: designation
    genre:
        label: Genres
        modelClass: DigitalArtisan\Enseignement\Models\Genre
        conditions: genre_id in (:filtered)
        nameFrom: designation        
    langue:
        label: Langues
        modelClass: DigitalArtisan\Enseignement\Models\Langue
        conditions: langue_id in (:filtered)
        nameFrom: designation
    is_actif:
        label: Actif
        type: switch
        default: 2
        conditions:
            - is_actif <> true
            - is_actif = true