name: Enseignants
form: $/digart/ecole/models/enseignant/fields.yaml
modelClass: DigArt\Ecole\Models\Enseignant
defaultRedirect: digart/ecole/enseignants
create:
    redirect: 'digart/ecole/enseignants/update/:id'
    redirectClose: digart/ecole/enseignants
update:
    redirect: digart/ecole/enseignants
    redirectClose: digart/ecole/enseignants
