name: Programmes
form: $/digart/ecole/models/programme/fields.yaml
modelClass: DigArt\Ecole\Models\Programme
defaultRedirect: digart/ecole/programmes
create:
    redirect: 'digart/ecole/programmes/update/:id'
    redirectClose: digart/ecole/programmes
update:
    redirect: digart/ecole/programmes
    redirectClose: digart/ecole/programmes
