name: Cercles
form: $/digart/ecole/models/cercle/fields.yaml
modelClass: DigArt\Ecole\Models\Cercle
defaultRedirect: digart/ecole/cercles
create:
    redirect: 'digart/ecole/cercles/update/:id'
    redirectClose: digart/ecole/cercles
update:
    redirect: digart/ecole/cercles
    redirectClose: digart/ecole/cercles
