title: Volées
modelClass: DigArt\Ecole\Models\Volee
list: $/digart/ecole/models/volee/columns.yaml
recordUrl: 'digart/ecole/volees/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml