name: Volees
form: $/digart/ecole/models/volee/fields.yaml
modelClass: DigArt\Ecole\Models\Volee
defaultRedirect: digart/ecole/volees
create:
    redirect: 'digart/ecole/volees/update/:id'
    redirectClose: digart/ecole/volees
update:
    redirect: digart/ecole/volees
    redirectClose: digart/ecole/volees
