name: Ecoles
form: $/digart/ecole/models/ecole/fields.yaml
modelClass: DigArt\Ecole\Models\Ecole
defaultRedirect: digart/ecole/ecoles
create:
    redirect: 'digart/ecole/ecoles/update/:id'
    redirectClose: digart/ecole/ecoles
update:
    redirect: digart/ecole/ecoles
    redirectClose: digart/ecole/ecoles
