title: Ecoles
modelClass: DigitalArtisan\Enseignement\Models\Ecole
list: $/digitalartisan/enseignement/models/ecole/columns.yaml
recordUrl: 'digitalartisan/enseignement/ecoles/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
